# Generated by Django 4.2.4 on 2024-06-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_profile_name_remove_profile_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__last_name']},
        ),
    ]
