# Generated by Django 4.2.4 on 2024-01-07 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pulicado',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 16, 12, 2, 871606, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
