# Generated by Django 4.2.4 on 2024-01-07 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_pulicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pulicado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
