# Generated by Django 4.2.4 on 2024-01-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_pulicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulicado',
            new_name='publicado',
        ),
    ]
