# Generated by Django 4.2.4 on 2024-04-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('contenido', models.CharField(blank=True, max_length=300, verbose_name='Contenido')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de la consulta')),
            ],
            options={
                'verbose_name': 'formulario_contacto',
                'ordering': ['created'],
            },
        ),
    ]
